title: "Babilônia Productions"
description: "Babilônia Productions is a Rio de Janeiro-based production company creating high-impact lifestyle, fashion and documentary content for global brands and agencies."
url: "https://babiloniaproductions.com"
permalink: /blog/:title/

collections:
  case_studies:
    output: true
    permalink: /work/:path/

defaults:
  - scope:
      path: ""
      type: "case_studies"
    values:
      layout: "case-study"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - "BulkResizePhotos.com-7.zip"
  - "0703(4).mp4"
  - "Screen Recording 2026-07-03 at 11.48.43.mov"
  - Gemfile
  - Gemfile.lock
  - node_modules
